name: CI

on:
  push: { branches: [ master ] }

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Container
        uses: docker/build-push-action@v1
        with:
          path: ./
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: donbeave/java-swiss-knife
          tag_with_ref: true
          tag_with_sha: true
